#!/usr/bin/with-contenv bash

set -ex
rm -rf /var/www/html/web/wp/wp-content/mu-plugins/shifter-artifact-helper
cp -r /usr/local/src/shifter-artifact-helper /var/www/html/web/wp/wp-content/mu-plugins/
